export const ACTION = {
  MODAL: {
    MODAL_OPEN: 'MODAL/MODAL_OPEN',
    MODAL_CLOSE: 'MODAL/MODAL_CLOSE',
  },
  USER_BIO: {
    SET_USER_BIO: 'USER_BIO/SET_USER_BIO',
    CLEAR_USER_BIO: 'USER_BIO/CLEAR_USER_BIO',
  },
};
