import React from 'react';
import MainLayout from '@/components/layouts/main-layout/MainLayout';
import Typography from '@material-ui/core/Typography';

function App() {
  return (
    <MainLayout>
      <Typography
        variant="h1"
        gutterBottom
      >
        subtitle1
      </Typography>
      <Typography
        variant="h1"
        gutterBottom
      >
        subtitle1
      </Typography>
      <Typography
        variant="h1"
        gutterBottom
      >
        subtitle1
      </Typography>
      <Typography
        variant="h1"
        gutterBottom
      >
        subtitle1
      </Typography>
      <Typography
        variant="h1"
        gutterBottom
      >
        subtitle1
      </Typography>
      <Typography
        variant="h1"
        gutterBottom
      >
        subtitle1
      </Typography>
      <Typography
        variant="h1"
        gutterBottom
      >
        subtitle1
      </Typography>
      <Typography
        variant="h1"
        gutterBottom
      >
        subtitle1
      </Typography>
      <Typography
        variant="h1"
        gutterBottom
      >
        subtitle1
      </Typography>
      <Typography
        variant="h1"
        gutterBottom
      >
        subtitle1
      </Typography>
      <Typography
        variant="h1"
        gutterBottom
      >
        subtitle1
      </Typography>
      <Typography
        variant="h1"
        gutterBottom
      >
        subtitle1
      </Typography>
      <Typography
        variant="h1"
        gutterBottom
      >
        subtitle1
      </Typography>
      <Typography
        variant="h1"
        gutterBottom
      >
        subtitle1
      </Typography>
      <Typography
        variant="h1"
        gutterBottom
      >
        subtitle1
      </Typography>
      <Typography
        variant="h1"
        gutterBottom
      >
        subtitle1
      </Typography>
      <Typography
        variant="h1"
        gutterBottom
      >
        subtitle1
      </Typography>
      <Typography
        variant="h1"
        gutterBottom
      >
        subtitle1
      </Typography>
      <Typography
        variant="h1"
        gutterBottom
      >
        subtitle1
      </Typography>
      <Typography
        variant="h1"
        gutterBottom
      >
        subtitle1
      </Typography>
      <Typography
        variant="h1"
        gutterBottom
      >
        subtitle1
      </Typography>
      <Typography
        variant="h1"
        gutterBottom
      >
        subtitle1
      </Typography>
      <Typography
        variant="h1"
        gutterBottom
      >
        subtitle1
      </Typography>
      <Typography
        variant="h1"
        gutterBottom
      >
        subtitle1
      </Typography>
      <Typography
        variant="h1"
        gutterBottom
      >
        subtitle1
      </Typography>
      <Typography
        variant="h1"
        gutterBottom
      >
        subtitle1
      </Typography>
      <Typography
        variant="h1"
        gutterBottom
      >
        subtitle1
      </Typography>
      <Typography
        variant="h1"
        gutterBottom
      >
        subtitle1
      </Typography>
      <Typography
        variant="h1"
        gutterBottom
      >
        subtitle1
      </Typography>
      <Typography
        variant="h1"
        gutterBottom
      >
        subtitle1
      </Typography>
      <Typography
        variant="h1"
        gutterBottom
      >
        subtitle1
      </Typography>
      <Typography
        variant="h1"
        gutterBottom
      >
        subtitle1
      </Typography>
      <Typography
        variant="h1"
        gutterBottom
      >
        subtitle1
      </Typography>
    </MainLayout>
  );
}

export default App;
